### ISSUE TITLE
Autocomplete gives extra closing bracket.

### ISSUE THREAD

**Issue by dijit** [korekontrol/vscode-saltstack#1]
When typing `{%` the auto completion seems to give me a completion of `{%%}}` (placing my cursor in the centre of the %'s)

Unfortunately, this is not syntactically valid Jinja2

**Comment by heschlie** [comment]
Seeing the same thing.

**Comment by ralish** [comment]
Ditto. Super annoying as you can easily forget to remove the extra bracket and then get parsing errors.

**Comment by ralish** [comment]
A quick workaround is to add the following to your VS Code settings:
`
    "[sls]": {
        "editor.autoClosingBrackets": "never"
    }
`

**Comment by kevinlong206** [comment]
Seeing the same, thanks @ralish for the workaround .

**Comment by Rossn2** [comment]
This is actually because autocomplete is configured for a single `{ `, thus giving you an extra `} `bracket if trying to use others such as `{{, {%, {#`.

If you want to fix this and still use autocomplete brackets for everything else:

1. Open: jinja.configuration.json
2. change: `["{", "}"]`
3. to: `["{{", "}}"]`

**Comment by marek-obuchowicz** [comment]
Does latest issue of vscode plugin fix it for you?

**Comment by heschlie** [comment]
@marek-obuchowicz It seems to have fixed it for me

**Comment by ralish** [comment]
The new v0.0.6 release doesn't appear to be published yet to the VS Code marketplace?

**Comment by ralish** [comment]
Nevermind, I've got it now and can confirm it looks to have fixed the issue.

I note that a changelog entry hasn't been published with the new version which may have been the cause of my confusion? Not sure if the update genuinely wasn't available at the time or I looked at the changelog in VS Code and just assumed it wasn't yet published after I'd manually checked for updates.

**Comment by marek-obuchowicz** [comment]
@ralish you are right, my bad - i didn't add the change to `changelog.md` before pushing it to Marketplace. At the moment marketplace doesn't allow to push `0.0.6` again - changelog will be published correctly with next release.
