### ISSUE TITLE
Installation issue v0.0.8

### ISSUE THREAD

**Issue by avocadotruck94** [korekontrol/vscode-saltstack#12]
Hi,

I'm running into an installation issue with v0.0.8 on the following vscode setup

Version: 1.54.3
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-48-generic snap
Ubuntu 20.04 LTS 64-bit

The extension doesn't get loaded after installation, even after window reload and vscode restart. The issue manifests through the lack of color/syntax highlighting and no salt related auto completion suggestions when pressing ctrl+space (just the default vscode text suggestions). I first thought this might be due to conflict with Better Jinja and salt-lint extensions but still had the same issue after uninstalling them.

The workaround for now has been

1. Install extension
2. Install a lower version which enables the "Reload required" button
3. Press the "Reload required" button
4. Update to the latest version
5. Press the "Reload required" button again 

This seems to load the extension properly. Perhaps there is a way to reload the extension directly through the command palette?

Either way, minor issue but thought I'd mention it.

Best regards

**Comment by hatifnatt** [comment]
Faced with same issue

Version: 1.54.3
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.14-1-MANJARO

After installation of version 0.0.8 only `SaltStack (tst)` language available for selection. Workaround described above helped `SaltStack (sls)` language appeared in selection dialogue, after downgrade to version 0.0.6. But after upgrade to 0.0.8 it's gone and only `SaltStack (tst)` available.

**Comment by marek-obuchowicz** [comment]
Release 0.0.9 has arrived
